# Generated by Django 2.1.7 on 2019-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuck',
            name='nick',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
