# Generated by Django 2.1.7 on 2019-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucks', '0002_auto_20190312_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuck',
            name='nick',
            field=models.CharField(max_length=20),
        ),
    ]
